name: 'Publish Release'
description: 'Publish the release'
inputs:
  branch-prefix:
    description: 'Branch Prefix'
    required: true
    default: 'release-v'

runs:
  using: 'composite'
  steps:
    - id: get-release-notes
      shell: bash
      run: node ${{ github.action_path }}/dist/index.js
    - id: create-github-release
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/create-github-release.sh \
          ${{ inputs.branch-prefix }} \
          ${{ steps.get-release-notes.outputs.RELEASE_NOTES }}
