name: 'Publish Release'
description: 'Publish the release'
inputs:
  branch-prefix:
    description: 'Branch Prefix'
    required: true
    default: 'release/'

runs:
  using: 'composite'
  steps:
    - id: get-release-version
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/get-release-version.sh \
          ${{ inputs.branch-prefix }}
    # This sets RELEASE_NOTES as an environment variable, which is expected
    # by the create-github-release step.
    - id: get-release-notes
      shell: bash
      run: node ${{ github.action_path }}/dist/index.js
      env:
        RELEASE_VERSION: ${{ steps.get-release-version.outputs.RELEASE_VERSION }}
    - id: create-github-release
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/create-github-release.sh \
          ${{ steps.get-release-version.outputs.RELEASE_VERSION }}
