name: 'Publish Release'
description: 'Publish the release'
inputs:
  release-branch-prefix:
    description: 'The prefix used for branches of release PRs.'
    default: 'release/'
    required: true
  npm-token:
    description: 'The token used for npm publishing. Publishing to npm will be skipped if omitted.'
    required: false

outputs:
  release-version:
    description: 'The version of the release'
    value: ${{ steps.get-release-version.outputs.RELEASE_VERSION }}

runs:
  using: 'composite'
  steps:
    - id: get-release-version
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/get-release-version.sh \
          ${{ inputs.release-branch-prefix }}
    # This sets RELEASE_NOTES as an environment variable, which is expected
    # by the create-github-release step.
    - id: get-release-notes
      shell: bash
      run: node ${{ github.action_path }}/dist/index.js
      env:
        RELEASE_VERSION: ${{ steps.get-release-version.outputs.RELEASE_VERSION }}
    - id: create-github-release
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/create-github-release.sh \
          ${{ steps.get-release-version.outputs.RELEASE_VERSION }}

    - id: Publish
      shell: bash
      run: ${{ github.action_path }}/scripts/npm-publish.sh
      env:
        NPM_TOKEN: ${{ inputs.npm-token }}
