name: Build, Lint, and Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-lint-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: yarn --frozen-lockfile
      - run: yarn allow-scripts
      - run: yarn build
      - run: git diff --quiet || { echo 'working directory dirty after "yarn build"'; exit 1; }
      - run: yarn lint
      - run: yarn test
  # tests to ensure get-release-packages.sh functions as expected
  updated-packages-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Get Latest Version from npm
        id: latestrelease
        run: echo "releasever=$(npm view MetaMask/snaps-skunkworks version --workspaces=false)" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v3
        with:
          repository: MetaMask/snaps-skunkworks
          ref: v${{ steps.latestrelease.outputs.releasever }}
          path: skunkworks
      - uses: actions/checkout@v3
        with:
          path: action-publish-release
      - name: Get Packages
        id: get-packages
        run: |
          cd skunkworks || exit
          WORKSPACES=$(yarn workspaces list --verbose --json)
          PUBLIC_PACKAGES=()
          PRIVATE_PACKAGE=()

          while read -r location name; do
            if [[ "$name" != "root" ]]; then
              PRIVATE=$(jq --raw-output '.private' "$location/package.json")
              if [[ "$PRIVATE" != true && "${#PUBLIC_PACKAGES[@]}" -ne 3 ]]; then
                PUBLIC_PACKAGES+=("$location")
              fi
              if [[ "$PRIVATE" == true && "${#PRIVATE_PACKAGE[@]}" -ne 1 ]]; then
                PRIVATE_PACKAGE+=("$location")
              fi
            fi
          done< <(echo "$WORKSPACES" | jq --raw-output '"\(.location) \(.name)"')

          RELEASE_PACKAGES=("${PUBLIC_PACKAGES[@]}" "${PRIVATE_PACKAGE[@]}")
          IFS="," RELEASE_PACKAGES_FORMATTED="${RELEASE_PACKAGES[*]}"
          echo "RELEASE_PACKAGES=$RELEASE_PACKAGES_FORMATTED" >> "$GITHUB_OUTPUT"
      - name: Modify + Get RELEASE_PACKAGES lengths
        id: modify-get-release-packages
        run: |
          function update_manifest() {
            MANIFEST="${1}/package.json"
            MANIFEST_TEMP="${MANIFEST}_temp"
            VERSION=$(jq --raw-output .version "$MANIFEST")
            IFS='.' read -r -a VERSIONS <<< "$VERSION"
            MAJOR="${VERSIONS[0]}"
            MINOR="${VERSIONS[1]}"
            PATCH="${VERSIONS[2]}"
            if [[ "$2" == "unbump" ]]; then
              if [[ "$PATCH" == "0" ]]; then
                if [[ "$MINOR" == "0" ]]; then
                  # e.g. 10.0.0 -> 9.9.9
                  NEW_VERSION="$((MAJOR - 1)).9.9"
                else
                  # e.g. 1.10.0 -> 1.9.9
                  NEW_VERSION="${MAJOR}.$((MINOR - 1)).9"
                fi
              else
                # e.g. 1.2.10 -> 1.2.9
                NEW_VERSION="${MAJOR}.${MINOR}.$((PATCH - 1))"
              fi
            else
              # e.g. 1.0.0 -> 1.0.1
              NEW_VERSION="${MAJOR}.${MINOR}.$((PATCH + 1))"
            fi
            jq --arg version "$NEW_VERSION" '.version = $version' "$MANIFEST" > "$MANIFEST_TEMP"
            mv "$MANIFEST_TEMP" "$MANIFEST"
          }
          cd skunkworks || exit
          IFS="," read -r -a RELEASE_PACKAGES <<< "${{ steps.get-packages.outputs.RELEASE_PACKAGES }}"
          for i in {0..1}
          do
            update_manifest "${RELEASE_PACKAGES[$i]}" "bump"
          done
          update_manifest "${RELEASE_PACKAGES[2]}" "unbump"
          update_manifest "${RELEASE_PACKAGES[3]}" "bump"
          ../action-publish-release/scripts/get-release-packages.sh
      - name: Get modified RELEASE_PACKAGES lengths
        id: get-modified-updated-packages-length
        run: |
          echo "length=$(echo '${{ steps.modify-get-release-packages.outputs.RELEASE_PACKAGES }}' | jq '.packages | length')" >> "$GITHUB_OUTPUT"
      - name: Verify modified RELEASE_PACKAGES lengths
        run: |
          if [[ ${{ steps.get-modified-updated-packages-length.outputs.length }} -ne 3 ]]; then
            echo "modified RELEASE_PACKAGES is an unexpected length"
            exit 1
          fi;

  all-tests-pass:
    runs-on: ubuntu-20.04
    needs: [build-lint-test, updated-packages-test]
    steps:
      - run: echo "Great success"
