name: Publish Release

on:
  workflow_call:
    inputs:
      slack-icon-url:
        required: false
        type: string
        default: 'https://raw.githubusercontent.com/MetaMask/action-npm-publish/main/robo.png'
      slack-subteam:
        required: false
        type: string
        default: S042S7RE4AE # @metamask-npm-publishers
      slack-username:
        required: false
        type: string
        default: 'MetaMask bot'
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

permissions:
  contents: read

jobs:
  announce-release:
    name: Announce release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - id: name-hash
        name: Get Slack name and hash
        shell: bash
        if: inputs.slack-subteam != ''
        run: |
          NAME_VERSION_TEXT=$(jq --raw-output '.name + "@" + .version' package.json )
          NAME_VERSION_TEXT_STRIPPED="${NAME_VERSION_TEXT#@}"
          echo "NAME_VERSION=$NAME_VERSION_TEXT_STRIPPED" >> "$GITHUB_OUTPUT"
      - id: final-text
        name: Get Slack final text
        shell: bash
        if: inputs.slack-subteam != ''
        env:
          NAME_VERSION: ${{ steps.name-hash.outputs.NAME_VERSION }}
          REPOSITORY: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
          SUBTEAM: ${{ inputs.slack-subteam }}
        run: |
          DEFAULT_TEXT="\`${NAME_VERSION}\` is awaiting deployment :rocket: \n <https://github.com/${REPOSITORY}/actions/runs/${RUN_ID}/|→ Click here to review deployment>"
          FINAL_TEXT="$DEFAULT_TEXT"
          if [[ -n "$SUBTEAM" ]]; then
            FINAL_TEXT="<!subteam^${SUBTEAM}> $DEFAULT_TEXT"
          fi
          echo "FINAL_TEXT=$FINAL_TEXT" >> "$GITHUB_OUTPUT"
      - name: Post to a Slack channel
        if: inputs.slack-subteam != ''
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844
        with:
          payload: |
            {
              "text": "${{ steps.final-text.outputs.FINAL_TEXT }}",
              "icon_url": "${{ inputs.slack-icon-url }}",
              "username": "${{ inputs.slack-username }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        continue-on-error: true

  publish-release:
    name: Publish release
    environment: action-publish
    needs: announce-release
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: true
          persist-credentials: false
          ref: ${{ github.sha }}
          skip-install: true

      - name: Get token
        id: get-token
        uses: MetaMask/github-tools/.github/actions/get-token@v1
        with:
          token-exchange-url: ${{ vars.TOKEN_EXCHANGE_URL }}
          permissions: |
            contents: write

      - name: Publish release
        uses: MetaMask/action-publish-release@v3
        id: publish-release
        env:
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}

      - name: Update shorthand major version tag
        uses: MetaMask/github-tools/.github/actions/update-major-version-tag@v1
        with:
          release-version: ${{ steps.publish-release.outputs.release-version }}
          github-token: ${{ steps.get-token.outputs.token }}
